cleanup("3")
claim("#3 time is "..os.time())
claim("#3 wish text "..os.time().." at 0 0")
local graphics = string.format([===[[{"type":"text","options":{"x":%s,"y":%s,"text":"%s"}}]]===], 0, 0, "time-is-"..os.time())
claim("#3 wish you had graphics "..graphics)